version: "3.8"
services:

  db:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agnos
    volumes:
      - ./docker-volumes/pgdb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  agnos:
    build: .
    depends_on:
      db:
        condition: service_healthy
    image: storngpassword-service
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_NAME: agnos
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - ./docker-volumes/pgadmin:/var/lib/pgadmin
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge